### ISSUE TITLE
1.1.5 에서 바이러스가 오탐되는 듯 합니다.

### ISSUE THREAD

**Issue by klliop** [byungmeo/GersangPatchMaster#1]
1.1.5 에서 바이러스가 오탐되는 듯 합니다.
![image](https://user-images.githubusercontent.com/13827709/147069810-5f5ee560-2f3f-4c05-a8c6-55c64f8f5414.png)

**Comment by byungmeo** [comment]
탐지한 프로그램(V3, 윈도우 디펜더 등)이 뭔지 알 수 있을까요? 해결방법을 찾아보겠습니다

**Comment by klliop** [comment]
윈도우 디펜더입니다. 빠른 확인 감사드립니다.

**Comment by byungmeo** [comment]
![image](https://user-images.githubusercontent.com/37506142/147076314-fa627026-c127-455d-bc54-207f14ba78ae.png)

우선 마소측에는 재검사 요청을 보내놓긴 했는데, 영어 실력도 영 그렇고 제 말을 들어줄지 모르겠네요. 버전마다 새로 해줘야 하는 건 아닐지도 걱정되구요. 처음 해보는거라 저도 궁금하네요.

 결과가 나오면 알려드리겠습니다. 감사합니다.

**Comment by byungmeo** [comment]
![image](https://user-images.githubusercontent.com/37506142/147169087-17d612a0-0fc0-464d-bad7-c8e1b326203f.png)
![image](https://user-images.githubusercontent.com/37506142/147169103-c9772a5d-89af-4caa-b04a-723da16667fd.png)

악성프로그램 탐지에서 제외되었다고 연락받았습니다.
확인 부탁드리며 더 궁금하신 사항이 있으시면 코멘트 달아주세요.
