### ISSUE TITLE
[건의] 다클라 폴더이름 고정

### ISSUE THREAD

**Issue by klliop** [byungmeo/GersangPatchMaster#2]
다른 Station, Creator처럼 다클라 폴더 이름 고정기능을 건의드립니다.

**Comment by byungmeo** [comment]
초기값 설정토록 하겠습니다 이슈 트래커로 건의 해주셔서 감사합니다

**Comment by klliop** [comment]
번거로운 의견 수용 감사드립니다.

**Comment by byungmeo** [comment]
거상 다클라 스테이션으로 패치 마스터의 기능이 통합되었습니다.
말씀하신 부분은 이제 아예 Gersang2, Gersang3 라는 이름으로 고정하기로 결정하였습니다.
건의 해주셔서 감사합니다.
